<?php
/**
 * Inkfire Blueprint Child Theme Functions
 *
 * SECTIONS:
 * 1. Security & Core
 * 2. CORS & Fonts (Fixes cross-domain font loading)
 * 3. Styles & Enqueueing (Parent/Child theme setup)
 * 4. Maintenance (Weekly Debug Log Wipe)
 * 5. Auto-Migration (Self-healing URLs for Elementor)
 * 6. Reasons to Stay - Letter System (Core Includes & Logic)
 * 7. RTS Subscriber System
 * 8. Performance
 * 9. RTS API SAFEGUARDS (NEW - Embed Protection)
 * 10. Syndication Engine
 */

// =============================================================================
// 1. SECURITY & CORE
// =============================================================================

// Exit if accessed directly
if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

// Theme version constant (used for cache-busting enqueued assets)
// TEMPORARY: forced to time() to bust all caches after theme repair.
// Revert to wp_get_theme()->get('Version') once deployment is stable.
if ( ! defined( 'RTS_THEME_VERSION' ) ) {
    define( 'RTS_THEME_VERSION', (string) time() );
}

// =============================================================================
// 2. CORS & FONTS
// Handles cross-origin loading for fonts when sites are cloned/migrated.
// =============================================================================

add_action( 'send_headers', 'inkfire_add_cors_headers' );

function inkfire_add_cors_headers() {
    // Only run if we are sending headers (not CLI) and not already sent
    if ( headers_sent() ) {
        return;
    }

    // [SAFEGUARD MODIFICATION]
    // Skip this general logic for the Embed API. We handle that specifically 
    // in Section 9 to ensure wildcard (*) access for Wix/Squarespace.
    if ( isset($_SERVER['REQUEST_URI']) && strpos($_SERVER['REQUEST_URI'], '/rts/v1/embed') !== false ) {
        return;
    }

    $origin = get_http_origin();

    // If there is an origin (request is coming from another domain/subdomain)
    if ( $origin ) {
        // Allow all origins. This ensures that new domains created from the Blueprint
        // can load fonts from the source without "Blocked by CORS" errors.
        header( "Access-Control-Allow-Origin: " . $origin );
        header( "Access-Control-Allow-Methods: GET, OPTIONS" );
        header( "Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept" );
        header( "Vary: Origin" ); 
    }
}

// =============================================================================
// 3. STYLES & ENQUEUEING
// Auto-generated by Child Theme Configurator
// =============================================================================

// Handle RTL (Right-to-Left) language stylesheets
if ( ! function_exists( 'chld_thm_cfg_locale_css' ) ) {
    function chld_thm_cfg_locale_css( $uri ) {
        if ( empty( $uri ) && is_rtl() && file_exists( get_template_directory() . '/rtl.css' ) ) {
            $uri = get_template_directory_uri() . '/rtl.css';
        }
        return $uri;
    }
}
add_filter( 'locale_stylesheet_uri', 'chld_thm_cfg_locale_css' );

// Enqueue the Child Theme Styles and Dependencies
if ( ! function_exists( 'child_theme_configurator_css' ) ) {
    function child_theme_configurator_css() {
        wp_enqueue_style( 
            'chld_thm_cfg_child', 
            trailingslashit( get_stylesheet_directory_uri() ) . 'style.css', 
            array( 'hello-elementor', 'hello-elementor-theme-style', 'hello-elementor-header-footer' ) 
        );
    }
}
add_action( 'wp_enqueue_scripts', 'child_theme_configurator_css', 10 );

// =============================================================================
// 3A. RTS ADMIN UI SCOPE (Prevents CSS bleed across wp-admin)
// =============================================================================

if ( ! function_exists( 'rts_is_admin_screen' ) ) {
    /**
     * Detect whether the current admin request is an RTS screen.
     *
     * We intentionally over-match here to ensure every RTS endpoint is covered,
     * while still keeping styles scoped to those pages only.
     */
    function rts_is_admin_screen( $hook = '' ) {
        if ( ! is_admin() ) {
            return false;
        }

        // Safe guards
        $post_type = '';
        $taxonomy  = '';
        $page      = '';

        if ( function_exists( 'get_current_screen' ) ) {
            $screen = get_current_screen();
            if ( $screen ) {
                $post_type = isset( $screen->post_type ) ? (string) $screen->post_type : '';
                $taxonomy  = isset( $screen->taxonomy ) ? (string) $screen->taxonomy : '';
            }
        }

        $page = isset( $_GET['page'] ) ? (string) $_GET['page'] : '';

        // RTS post types + taxonomies
        $rts_post_types = array( 'letter', 'rts_feedback', 'rts_subscriber', 'rts_newsletter' );
        $rts_taxonomies = array( 'rts_feeling', 'rts_tone' );

        if ( $post_type && in_array( $post_type, $rts_post_types, true ) ) {
            return true;
        }

        if ( $taxonomy && in_array( $taxonomy, $rts_taxonomies, true ) ) {
            return true;
        }

        // Known RTS admin pages
        if ( $page && ( strpos( $page, 'rts-' ) === 0 || strpos( $page, 'rts_' ) === 0 ) ) {
            return true;
        }

        // Hook based fallback (covers edit.php?post_type=... and letter subpages)
        if ( $hook && ( strpos( $hook, 'rts-' ) !== false || strpos( $hook, 'letter_page_' ) !== false || strpos( $hook, 'rts_subscriber_page_' ) !== false ) ) {
            return true;
        }

        // URL fallback (last resort)
        if ( isset( $_SERVER['REQUEST_URI'] ) ) {
            $uri = (string) $_SERVER['REQUEST_URI'];
            if ( strpos( $uri, 'post_type=letter' ) !== false ||
                 strpos( $uri, 'post_type=rts_feedback' ) !== false ||
                 strpos( $uri, 'post_type=rts_subscriber' ) !== false ||
                 strpos( $uri, 'post_type=rts_newsletter' ) !== false ||
                 strpos( $uri, 'page=rts-' ) !== false ||
                 strpos( $uri, 'page=rts_' ) !== false ) {
                return true;
            }
        }

        return false;
    }
}

add_filter( 'admin_body_class', function( $classes ) {
    $hook = isset( $GLOBALS['hook_suffix'] ) ? (string) $GLOBALS['hook_suffix'] : '';
    if ( rts_is_admin_screen( $hook ) ) {
        $classes .= ' rts-admin-scope';
    }
    return $classes;
} );

add_action( 'admin_enqueue_scripts', function( $hook ) {
    if ( ! function_exists( 'rts_is_admin_screen' ) || ! rts_is_admin_screen( (string) $hook ) ) {
        return;
    }

    $css_rel  = '/assets/css/rts-admin-complete.css';
    $css_path = get_stylesheet_directory() . $css_rel;
    if ( ! file_exists( $css_path ) ) {
        return;
    }

    // Avoid double-enqueue from subsystem files.
    if ( wp_style_is( 'rts-admin-complete', 'enqueued' ) ) {
        return;
    }

    wp_enqueue_style(
        'rts-admin-complete',
        get_stylesheet_directory_uri() . $css_rel,
        array(),
        (string) filemtime( $css_path )
    );
}, 20 );

// =============================================================================
// 4. MAINTENANCE: WEEKLY DEBUG LOG WIPE
// Empties debug.log once a week. Fixes 'as_next_scheduled_action' crash.
// =============================================================================

// A. Add "Weekly" timing to WordPress if it doesn't exist
add_filter( 'cron_schedules', 'inkfire_add_weekly_cron_schedule' );
function inkfire_add_weekly_cron_schedule( $schedules ) {
    $schedules['weekly'] = [
        'interval' => WEEK_IN_SECONDS,
        'display'  => __( 'Once Weekly' )
    ];
    return $schedules;
}

// B. Schedule the event on 'init' (Safe for Action Scheduler)
add_action( 'init', 'inkfire_schedule_log_wipe' );
function inkfire_schedule_log_wipe() {
    if ( ! wp_next_scheduled( 'inkfire_weekly_wipe_debug_log' ) ) {
        wp_schedule_event( time(), 'weekly', 'inkfire_weekly_wipe_debug_log' );
    }
}

// C. The Wiper Function: Empties the file
add_action( 'inkfire_weekly_wipe_debug_log', 'inkfire_clear_debug_log' );
function inkfire_clear_debug_log() {
    $log_path = WP_CONTENT_DIR . '/debug.log';

    if ( file_exists( $log_path ) ) {
        // Erase file contents (0 bytes)
        file_put_contents( $log_path, '' );
        // Add a timestamp so you know it ran
        error_log( '--- Log Cleared by Inkfire Schedule: ' . date( 'Y-m-d H:i:s' ) . ' ---' );
    }
}

// D. Cleanup: Remove schedule if theme is switched
add_action( 'switch_theme', 'inkfire_unschedule_log_wipe' );
function inkfire_unschedule_log_wipe() {
    $timestamp = wp_next_scheduled( 'inkfire_weekly_wipe_debug_log' );
    if ( $timestamp ) {
        wp_unschedule_event( $timestamp, 'inkfire_weekly_wipe_debug_log' );
    }
}

// =============================================================================
// 5. AUTO-MIGRATION (Self-Healing URLs)
// Automatically updates Elementor URLs when the site is moved to a new domain.
// =============================================================================

add_action( 'admin_init', 'inkfire_auto_migrate_urls' );

function inkfire_auto_migrate_urls() {
    // 1. Safety Checks: Only run for admins and if Elementor exists
    if ( ! current_user_can( 'manage_options' ) || ! class_exists( '\Elementor\Utils' ) ) {
        return;
    }

    // 2. Get the current site domain and the stored "last known" domain
    $current_domain = untrailingslashit( get_site_url() );
    $stored_domain  = get_option( 'inkfire_last_known_domain' );

    // 3. First Run (Blueprint Setup): Save current domain as baseline
    if ( empty( $stored_domain ) ) {
        update_option( 'inkfire_last_known_domain', $current_domain );
        return;
    }

    // 4. Migration Detected: Domain has changed
    if ( $stored_domain !== $current_domain ) {
        
        try {
            // A. Run Elementor's built-in Search & Replace
            \Elementor\Utils::replace_urls( $stored_domain, $current_domain );

            // B. Regenerate Elementor CSS Files (Fixes font paths)
            if ( class_exists( '\Elementor\Plugin' ) ) {
                \Elementor\Plugin::$instance->files_manager->clear_cache();
            }

            // C. Update the database record to the new domain
            update_option( 'inkfire_last_known_domain', $current_domain );

            // D. Leave a success notice for the admin
            add_action( 'admin_notices', function() use ( $stored_domain, $current_domain ) {
                echo '<div class="notice notice-success is-dismissible">';
                echo "<p><strong>Inkfire Blueprint:</strong> Domain migration detected. Auto-updated URLs from <em>$stored_domain</em> to <em>$current_domain</em> and regenerated CSS.</p>";
                echo '</div>';
            } );

            // E. Log to debug.log
            error_log( "Inkfire Auto-Migrate: Replaced $stored_domain with $current_domain" );

        } catch ( Exception $e ) {
            error_log( 'Inkfire Auto-Migrate Error: ' . $e->getMessage() );
        }
    }
}


/**
 * Site Mods: Share Buttons JS (Footer, Modular)
 * Uses links/buttons with class .share-btn and data-platform="facebook|x|threads|reddit|whatsapp|email|copy"
 */

add_action('wp_enqueue_scripts', function () {

    // Front-end only
    if (is_admin()) {
        return;
    }

    // Ensure jQuery isn't required. We'll attach to a core script handle.
    // If your theme doesn't enqueue a stable handle, 'wp-util' is a safe core handle.
    wp_enqueue_script('wp-util');

    $js = <<<JS
(function () {

  function getPageData() {
    return {
      url: encodeURIComponent(window.location.href),
      title: encodeURIComponent(document.title)
    };
  }

  function getShareUrls(data) {
    return {
      facebook: "https://www.facebook.com/sharer/sharer.php?u=" + data.url,
      x: "https://twitter.com/intent/tweet?url=" + data.url,
      threads: "https://www.threads.net/intent/post?text=" + data.url,
      reddit: "https://www.reddit.com/submit?url=" + data.url,
      whatsapp: "https://api.whatsapp.com/send?text=" + data.url,
      email: "mailto:?subject=" + data.title + "&body=" + data.url
    };
  }

  function initCopyButton(button) {
    button.addEventListener("click", function () {
      var rawUrl = window.location.href;

      if (navigator.clipboard && navigator.clipboard.writeText) {
        navigator.clipboard.writeText(rawUrl);
        return;
      }

      // Fallback for older browsers
      var temp = document.createElement("textarea");
      temp.value = rawUrl;
      temp.setAttribute("readonly", "");
      temp.style.position = "absolute";
      temp.style.left = "-9999px";
      document.body.appendChild(temp);
      temp.select();
      try { document.execCommand("copy"); } catch (e) {}
      document.body.removeChild(temp);
    });
  }

  function initShareButtons() {
    var pageData = getPageData();
    var shareUrls = getShareUrls(pageData);

    document.querySelectorAll(".share-btn").forEach(function (button) {
      var platform = button.dataset.platform;
      if (!platform) return;

      if (platform === "copy") {
        initCopyButton(button);
        return;
      }

      if (shareUrls[platform]) {
        button.setAttribute("href", shareUrls[platform]);
      }
    });
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", initShareButtons);
  } else {
    initShareButtons();
  }

})();
JS;

    wp_add_inline_script('wp-util', $js, 'after');
});


/* =====================================================
   RTS – Dynamic Site Stats (3-stat row)
   ===================================================== */

/**
 * Helper: get theme mod with fallback
 */
if (!function_exists('rts_stat')) {
  function rts_stat($key, $default = '') {
    $val = get_theme_mod($key, $default);
    return ($val !== '' ? $val : $default);
  }
}

/**
 * CHANGE THIS if your CPT slug is different
 * e.g. 'letters', 'rts_letter'
 */
if (!defined('RTS_LETTER_CPT')) {
  define('RTS_LETTER_CPT', 'letter');
}

/**
 * Get total submitted letters
 */
function rts_get_letters_submitted_count(): int {
  $q = new WP_Query([
    'post_type'      => RTS_LETTER_CPT,
    'post_status'    => ['publish'], // add 'pending' if you want
    'posts_per_page' => 1,
    'fields'         => 'ids',
  ]);

  return (int) $q->found_posts;
}

/**
 * REST endpoint (cache-safe)
 * /wp-json/rts/v1/letter-count
 */
add_action('rest_api_init', function () {
  register_rest_route('rts/v1', '/letter-count', [
    'methods'  => 'GET',
    'permission_callback' => '__return_true',
    'callback' => function () {
      return [
        'count' => rts_get_letters_submitted_count(),
      ];
    },
  ]);
});

/**
 * Inject frontend JS to update count
 */
add_action('wp_enqueue_scripts', function () {

  if (is_admin()) return;

  wp_enqueue_script('wp-util');

  $rest_url = esc_url_raw( rest_url('rts/v1/letter-count') );

  $js = <<<JS
(function () {

  function format(n){
    try { return new Intl.NumberFormat().format(n); }
    catch(e){ return n; }
  }

  function update(){
    var el = document.getElementById('rts-letters-submitted');
    if(!el) return;

    fetch('{$rest_url}')
      .then(r => r.json())
      .then(d => {
        if(!d || typeof d.count === 'undefined') return;
        el.textContent = format(parseInt(d.count,10) || 0);
      })
      .catch(() => {});
  }

  if(document.readyState === 'loading'){
    document.addEventListener('DOMContentLoaded', update);
  } else {
    update();
  }

})();
JS;

  wp_add_inline_script('wp-util', $js, 'after');
});

/**
 * Shortcode: [rts_site_stats_row]
 */
// [rts_site_stats_row] is registered in /inc/shortcodes.php (single source of truth).


// =============================================================================
// 6. REASONS TO STAY - LETTER SYSTEM
// Complete V1 system for letter management, submission, and viewing
// =============================================================================

/**
 * Load RTS System Components
 */
// Include the Moderation Engine FIRST to ensure REST routes register early
$rts_engine_path = get_stylesheet_directory() . '/inc/rts-moderation-engine.php';
if (file_exists($rts_engine_path)) {
    require_once $rts_engine_path;
}
// Include zombie queue hard reset utilities (fixes for stuck queue)
$rts_hard_reset_path = get_stylesheet_directory() . '/inc/rts-zombie-queue-hard-reset.php';
if (file_exists($rts_hard_reset_path)) {
    require_once $rts_hard_reset_path;
}

// === Enterprise modules (independent includes, fail-soft) ===

// Context-aware safety scanner (differentiates "I want to die" from "you should die")
$safety_path = get_stylesheet_directory() . '/inc/rts-context-aware-safety.php';
if (file_exists($safety_path)) {
    require_once $safety_path;
}

// Streaming importer for massive files (300MB+, 20-50k letters)
$importer_path = get_stylesheet_directory() . '/inc/rts-streaming-importer.php';
if (file_exists($importer_path)) {
    require_once $importer_path;
}

// Multilingual support (11 languages with auto-detection)
$multilingual_path = get_stylesheet_directory() . '/inc/rts-multilingual.php';
if (file_exists($multilingual_path)) {
    require_once $multilingual_path;
}


// Core includes with file_exists() checks for safety
$core_includes = [
    'security.php',
    'cpt-letters-complete.php',
    'rts-rest-api.php',
    'rts-bulk-jobs.php',
    'shortcodes.php',
    'logger.php',
    'rts-google-translate.php',
    'rts-quick-exit.php',
];

foreach ($core_includes as $file) {
    $path = get_stylesheet_directory() . '/inc/' . $file;
    if (file_exists($path)) {
        require_once $path;
    } else {
        error_log('RTS Theme: Missing required file - ' . $file);
    }
}



/**
 * Get site stats with manual override support
 * Use in Elementor: rts_get_stat('letters_delivered')
 */
function rts_get_stat($stat_type) {
    global $wpdb;

    switch ($stat_type) {
        case 'letters_delivered':
            // Live count from database
            $live = (int) $wpdb->get_var($wpdb->prepare(
                "SELECT COUNT(*) FROM {$wpdb->posts} WHERE post_type = %s AND post_status = %s",
                'letter',
                'publish'
            ));
            // Additive offset (manual marketing number added to live data)
            $offset = (int) get_option('rts_manual_stats_letters', 0);
            return number_format($live + $offset);

        case 'helpful_percentage':
            // Live calculation from database
            $thumbs_up = (int) $wpdb->get_var($wpdb->prepare(
                "SELECT COALESCE(SUM(meta_value), 0) FROM {$wpdb->postmeta} WHERE meta_key = %s",
                'thumbs_up'
            ));
            $thumbs_down = (int) $wpdb->get_var($wpdb->prepare(
                "SELECT COALESCE(SUM(meta_value), 0) FROM {$wpdb->postmeta} WHERE meta_key = %s",
                'thumbs_down'
            ));
            $total = $thumbs_up + $thumbs_down;
            $percent = ($total > 0) ? round(($thumbs_up / $total) * 100) : 0;
            // Additive offset (e.g. +5 to nudge displayed percentage)
            $offset = (int) get_option('rts_manual_stats_helpful', 0);
            $percent = max(0, min(100, $percent + $offset));
            return $percent . '%';

        case 'letters_submitted':
            // Live count (published + pending)
            $count = wp_count_posts('letter');
            $live = (int) $count->publish + (int) $count->pending;
            // Additive offset
            $offset = (int) get_option('rts_manual_stats_submissions', 0);
            return number_format($live + $offset);

        default:
            return '0';
    }
}

// Make function available for Elementor
add_shortcode('rts_stat', function($atts) {
    $atts = shortcode_atts(['type' => 'letters_delivered'], $atts);
    return rts_get_stat($atts['type']);
});

/**
 * Get site statistics with manual override support
 * Use this function in shortcodes/templates to get consistent stats
 */
function rts_get_site_stats() {
    // Manual offsets (legacy-compatible)
    $stats_override = get_option('rts_stats_override', ['enabled' => 0]);

    global $wpdb;

    // Live totals (always calculated)
    $live_letters_submitted = (int) wp_count_posts('letter')->publish;

    $live_letters_delivered = (int) $wpdb->get_var("
        SELECT SUM(meta_value)
        FROM {$wpdb->postmeta}
        WHERE meta_key = 'view_count'
    ");

    // Feel better percentage (stored option, or sensible default)
    $live_feel_better_percent = (float) get_option('rts_feel_better_percentage', 85.7);

    // If "override" is enabled, treat provided values as OFFSETS (never as replacements),
    // so the counters remain live and continue to increase.
    if (!empty($stats_override['enabled'])) {
        $off_submitted = (int) ($stats_override['offset_submitted'] ?? $stats_override['total_letters'] ?? 0);
        $off_delivered = (int) ($stats_override['offset_delivered'] ?? $stats_override['letters_delivered'] ?? 0);

        // Feel-better can be overridden as an absolute percentage (if provided), otherwise use live option.
        $feel_better_percent = isset($stats_override['feel_better_percent']) && $stats_override['feel_better_percent'] !== ''
            ? (float) $stats_override['feel_better_percent']
            : $live_feel_better_percent;

        return [
            // legacy keys
            'total_letters'       => $live_letters_submitted + $off_submitted,
            // preferred keys
            'letters_submitted'   => $live_letters_submitted + $off_submitted,
            'letters_delivered'   => $live_letters_delivered + $off_delivered,
            'feel_better_percent' => (float) $feel_better_percent,
            'using_override'      => true,
        ];
    }

    return [
        // legacy key
        'total_letters'       => $live_letters_submitted,
        // preferred keys
        'letters_submitted'   => $live_letters_submitted,
        'letters_delivered'   => $live_letters_delivered,
        'feel_better_percent' => (float) $live_feel_better_percent,
        'using_override'      => false,
    ];
}

/**
 * Export letters to CSV
 */
// NOTE: Manual processing admin-post handlers are registered inside inc/cron-processing.php
// (RTS_Cron_Processing::init). Keeping them in one place prevents double-execution.

// Boot client-friendly admin menu and clean list columns
if (class_exists('RTS_Letter_Management_Admin')) {
    new RTS_Letter_Management_Admin();
}

/**
 * Enqueue RTS Frontend Assets
 */
add_action('wp_enqueue_scripts', 'rts_enqueue_frontend_assets');
function rts_enqueue_frontend_assets() {
    // Only load on frontend
    if (is_admin()) return;

    $theme = wp_get_theme();
    $ver = $theme && $theme->exists() ? $theme->get('Version') : '2.0.1';

    // Font Awesome (do NOT load via CSS @import; browsers will ignore mid-file @import rules)
    wp_enqueue_style(
        'rts-fontawesome',
        'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css',
        [],
        '6.5.1'
    );

    wp_enqueue_style(
        'rts-google-fonts',
        'https://fonts.googleapis.com/css2?family=Special+Elite&family=Inter:wght@400;500;600&display=swap',
        [],
        null
    );

    // Main CSS
    $css_file = get_stylesheet_directory() . '/assets/css/rts-system.css';
    $css_ver  = file_exists($css_file) ? (string) filemtime($css_file) : $ver;
    $css_ver .= '-v4';

    // Dev-friendly cache busting (admin only): lets you iterate on CSS/JS without
    // touching theme version numbers, even if a proxy/CDN is being sticky.
    wp_enqueue_style(
        'rts-system',
        get_stylesheet_directory_uri() . '/assets/css/rts-system.css',
        ['rts-fontawesome','rts-google-fonts'],
        $css_ver
    );

    // Main JavaScript
    $js_file = get_stylesheet_directory() . '/assets/js/rts-system.js';
    $js_ver  = file_exists($js_file) ? (string) filemtime($js_file) : $ver;
    $js_ver .= '-v4';
    wp_enqueue_script(
        'rts-system',
        get_stylesheet_directory_uri() . '/assets/js/rts-system.js',
        [],
        $js_ver,
        true
    );

    // LiteSpeed-friendly: allow defer without breaking DOM-ready usage
    wp_script_add_data('rts-system', 'defer', true);

    
    
    // Provide REST base URL (fixes viewer failures on subdirectory installs / language prefixes)
    // and a sensible request timeout to avoid infinite loading states.
    wp_localize_script('rts-system', 'RTS_CONFIG', [
        'restBase'  => esc_url_raw(rest_url('rts/v1/')),
        // Enable REST mode in the frontend letter viewer.
        // The JS will automatically fall back to admin-ajax.php on 403/404.
        'restEnabled' => true,
        'ajaxUrl'   => esc_url_raw(admin_url('admin-ajax.php')),
        // Optional, but helps in setups where security layers expect a REST nonce.
        'nonce'     => wp_create_nonce('wp_rest'),
        // Unique per page load; lets us de-dupe analytics if this script is initialised twice.
        'pageViewId' => function_exists('wp_generate_uuid4') ? wp_generate_uuid4() : (string) (microtime(true) . '-' . wp_rand()),
        'timeoutMs' => 9000,
    ]);
}

/**
 * Prevent Cloudflare Rocket Loader from rewriting the RTS script.
 * (Rocket Loader can break modern JS syntax, causing silent loading failures.)
 */
add_filter('script_loader_tag', function ($tag, $handle, $src) {
    if ($handle === 'rts-system' || $handle === 'rts-subscription-form') {
        // data-cfasync="false" disables Rocket Loader for this script.
        if (strpos($tag, 'data-cfasync') === false) {
            $tag = str_replace('<script ', '<script data-cfasync="false" ', $tag);
        }
    }
    return $tag;
}, 10, 3);


/**
 * Initialize default letter taxonomies
 * Run once on theme activation
 */
add_action('after_switch_theme', 'rts_initialize_taxonomies');
function rts_initialize_taxonomies() {
    // Check if already initialized
    if (get_option('rts_taxonomies_initialized')) {
        return;
    }
    
    // Wait for CPT to be registered
    if (!taxonomy_exists('letter_feeling')) {
        return;
    }
    
    // Add default feelings
    $feelings = ['hopeless', 'alone', 'anxious', 'grieving', 'tired', 'struggling'];
    foreach ($feelings as $feeling) {
        if (!term_exists($feeling, 'letter_feeling')) {
            wp_insert_term($feeling, 'letter_feeling');
        }
    }
    
    // Add default tones
    $tones = ['gentle', 'real', 'hopeful'];
    foreach ($tones as $tone) {
        if (!term_exists($tone, 'letter_tone')) {
            wp_insert_term($tone, 'letter_tone');
        }
    }
    
    // Mark as initialized
    update_option('rts_taxonomies_initialized', true);
}

// =============================================================================
// v2.0 ENTERPRISE FEATURES
// Monitoring, auto-tagging, social sharing, security
// =============================================================================

/**
 * Load v2.0 Enterprise Components
 */
// v2.x enterprise components
$rts_optional_includes = [
    'admin-preview.php',
    'ally-widget.php',
    'feedback-system.php',
];

foreach ($rts_optional_includes as $file) {
    $path = get_stylesheet_directory() . '/inc/' . $file;
    if (file_exists($path)) {
        require_once $path;
    }
}


/**
 * HARD DISABLE Social Image columns/renderers.
 * Rank Math (or other SEO plugins) can handle OG images.
 * This prevents admin thumbnail requests that can trigger 403 spam on some hosts.
 */
add_filter('manage_letter_posts_columns', function($cols){
    foreach (['social_image','social','rts_social','rts_social_image'] as $key) {
        if (isset($cols[$key])) unset($cols[$key]);
    }
    return $cols;
}, 999);

add_action('manage_letter_posts_custom_column', function($column, $post_id){
    if (in_array($column, ['social_image','social','rts_social','rts_social_image'], true)) {
        return;
    }
}, 0, 2);

/**
 * AJAX: Clear import progress
 */
add_action('wp_ajax_rts_clear_import_progress', 'rts_ajax_clear_import_progress');
function rts_ajax_clear_import_progress() {
    if (!check_ajax_referer('rts_dashboard_nonce', 'nonce', false)) {
        wp_send_json_error(['message' => 'Security check failed']);
    }

    if (!current_user_can('manage_options')) {
        wp_send_json_error(['message' => 'Insufficient permissions']);
    }

    delete_option('rts_import_progress');
    delete_option('rts_import_total');
    delete_option('rts_import_processed');
    delete_option('rts_import_status');
    delete_transient('rts_import_running');

    wp_send_json_success(['message' => 'Import progress cleared']);
}

// =============================================================================
// MODERATION LEARNING SYSTEM (v3.5.6+)
// Self-learning system that improves moderation accuracy over time
// =============================================================================

// Load and initialize the learning system
if (file_exists(get_stylesheet_directory() . '/inc/rts-moderation-learning.php')) {
    require_once get_stylesheet_directory() . '/inc/rts-moderation-learning.php';
    
    if (class_exists('RTS_Moderation_Learning')) {
        add_action('init', ['RTS_Moderation_Learning', 'init'], 15);
    }
}

/**
 * Add moderation feedback buttons to letter edit screen
 * Allows admins to rate moderation decisions for learning
 */
function rts_add_feedback_buttons($post) {
    if ($post->post_type !== 'letter') return;
    
    $current_flags = get_post_meta($post->ID, 'rts_flagged_keywords', true);
    if (empty($current_flags)) return;
    
    $existing_feedback = get_post_meta($post->ID, 'rts_moderation_feedback', true);
    ?>
    
    <div class="misc-pub-section rts-moderation-feedback" style="padding: 10px; border-top: 1px solid #ddd;">
        <h4 style="margin: 0 0 10px 0;">📊 Moderation Feedback</h4>
        <p style="margin: 0 0 10px 0; font-size: 13px;">Was the automatic moderation correct?</p>
        
        <?php if ($existing_feedback): ?>
            <div style="padding: 10px; background: #f0f6fc; border-radius: 4px; margin-bottom: 10px;">
                <strong>Previous feedback:</strong> <?php echo esc_html($existing_feedback['feedback']); ?>
                <?php if (!empty($existing_feedback['notes'])): ?>
                    <br><em><?php echo esc_html($existing_feedback['notes']); ?></em>
                <?php endif; ?>
            </div>
        <?php endif; ?>
        
        
        <?php $nonce = wp_create_nonce('rts_feedback_action'); ?>
        <div class="rts-feedback-controls" data-post-id="<?php echo (int) $post->ID; ?>" data-nonce="<?php echo esc_attr($nonce); ?>">
            <div style="display: flex; gap: 5px; margin-bottom: 10px; flex-wrap: wrap;">
                <button type="button" data-feedback="correct" class="button button-small rts-feedback-btn">
                    ✓ Correct
                </button>

                <button type="button" data-feedback="too_strict" class="button button-small rts-feedback-btn">
                    ← Too Strict
                </button>

                <button type="button" data-feedback="too_lenient" class="button button-small rts-feedback-btn">
                    → Too Lenient
                </button>
            </div>

            <textarea class="rts-feedback-notes" placeholder="Optional notes..." rows="2" style="width:100%; font-size: 12px;"></textarea>
            <p class="rts-feedback-status" style="margin:8px 0 0; font-size:12px; display:none;"></p>
        </div>

    </div>
    
    <?php
}
add_action('post_submitbox_misc_actions', 'rts_add_feedback_buttons');




/**
 * Admin: moderation feedback buttons (no nested forms)
 */
function rts_enqueue_moderation_feedback_admin_js($hook) {
    // Only on post edit screens
    if (!in_array($hook, ['post.php', 'post-new.php'], true)) {
        return;
    }
    $screen = function_exists('get_current_screen') ? get_current_screen() : null;
    if (!$screen || $screen->post_type !== 'letter') {
        return;
    }

    $js = "(function(){\n"
        . "  if(typeof ajaxurl==='undefined') return;\n"
        . "  function post(data){\n"
        . "    var body = new URLSearchParams(data);\n"
        . "    return fetch(ajaxurl, {method:'POST', credentials:'same-origin', headers:{'Content-Type':'application/x-www-form-urlencoded; charset=UTF-8'}, body: body.toString()});\n"
        . "  }\n"
        . "  function setStatus(box, msg, ok){\n"
        . "    var el = box.querySelector('.rts-feedback-status');\n"
        . "    if(!el) return;\n"
        . "    el.style.display = 'block';\n"
        . "    el.style.color = ok ? '#0a7b34' : '#b32d2e';\n"
        . "    el.textContent = msg;\n"
        . "  }\n"
        . "  document.addEventListener('click', function(e){\n"
        . "    var btn = e.target && e.target.closest ? e.target.closest('.rts-feedback-btn') : null;\n"
        . "    if(!btn) return;\n"
        . "    var box = btn.closest('.rts-feedback-controls');\n"
        . "    if(!box) return;\n"
        . "    e.preventDefault();\n"
        . "    var postId = box.getAttribute('data-post-id') || '';\n"
        . "    var nonce = box.getAttribute('data-nonce') || '';\n"
        . "    var feedback = btn.getAttribute('data-feedback') || '';\n"
        . "    var notesEl = box.querySelector('.rts-feedback-notes');\n"
        . "    var notes = notesEl ? notesEl.value : '';\n"
        . "    btn.disabled = true;\n"
        . "    setStatus(box, 'Saving…', true);\n"
        . "    post({action:'rts_record_feedback_ajax', _wpnonce: nonce, post_id: postId, feedback: feedback, notes: notes})\n"
        . "      .then(function(r){ return r.json(); })\n"
        . "      .then(function(resp){\n"
        . "        if(resp && resp.success){\n"
        . "          setStatus(box, 'Saved. Thank you!', true);\n"
        . "        } else {\n"
        . "          var m = (resp && resp.data && resp.data.message) ? resp.data.message : 'Could not save feedback.';\n"
        . "          setStatus(box, m, false);\n"
        . "        }\n"
        . "      })\n"
        . "      .catch(function(){ setStatus(box, 'Network error. Please try again.', false); })\n"
        . "      .finally(function(){ btn.disabled = false; });\n"
        . "  });\n"
        . "})();";
    wp_add_inline_script('jquery-core', $js, 'after');
}
add_action('admin_enqueue_scripts', 'rts_enqueue_moderation_feedback_admin_js', 20);

// =============================================================================
// 7. RTS SUBSCRIBER SYSTEM
// Email subscription management with GDPR compliance
// =============================================================================

require_once get_stylesheet_directory() . '/subscribers/class-rts-subscriber-system.php';

/**
 * Manual activation for subscriber system
 */
add_action('admin_post_rts_activate_subscriber_system', 'rts_manual_activate_subscriber_system');
function rts_manual_activate_subscriber_system() {
    if (!current_user_can('manage_options')) {
        wp_die('Unauthorized');
    }
    check_admin_referer('rts_activate_system');
    
    $system = RTS_Subscriber_System();
    $system->activate();
    
    wp_redirect(add_query_arg(array(
        'page' => 'edit.php?post_type=rts_subscriber',
        'activated' => '1'
    ), admin_url()));
    exit;
}

/**
 * Show activation notice if database not initialized
 */
add_action('admin_notices', 'rts_show_activation_notice');
function rts_show_activation_notice() {
    $db_version = get_option('rts_subscriber_db_version', '0');
    
    if (version_compare($db_version, '1.0', '<')) {
        $activate_url = wp_nonce_url(
            admin_url('admin-post.php?action=rts_activate_subscriber_system'),
            'rts_activate_system'
        );
        ?>
        <div class="notice notice-warning">
            <p>
                <strong>RTS Subscriber System:</strong> Database tables not initialized. 
                <a href="<?php echo esc_url($activate_url); ?>" class="button button-primary">
                    Initialize Now
                </a>
            </p>
        </div>
        <?php
    }
}

// =============================================================================
// 8. PERFORMANCE: GZIP + REST API OPTIMISATIONS
// =============================================================================

/**
 * Force GZIP compression on REST API responses when zlib is available.
 * Reduces JSON payload size by ~90% on uncompressed hosts.
 */
add_filter( 'rest_pre_serve_request', 'rts_force_rest_gzip', 0, 4 );
function rts_force_rest_gzip( $served, $result, $request, $server ) {
    if (
        ! headers_sent()
        && extension_loaded( 'zlib' )
        && ! ini_get( 'zlib.output_compression' )
        && isset( $_SERVER['HTTP_ACCEPT_ENCODING'] )
        && stripos( $_SERVER['HTTP_ACCEPT_ENCODING'], 'gzip' ) !== false
    ) {
        ob_start( 'ob_gzhandler' );
    }
    return $served; // false = let WP continue normal serving
}

/**
 * Allow ?orderby=rand for the letter CPT REST endpoint (Data Diet prefetching).
 * Without this, WP REST rejects `rand` as an invalid orderby parameter.
 */
add_filter( 'rest_letter_collection_params', 'rts_allow_rand_orderby' );
function rts_allow_rand_orderby( $params ) {
    if ( isset( $params['orderby']['enum'] ) && ! in_array( 'rand', $params['orderby']['enum'], true ) ) {
        $params['orderby']['enum'][] = 'rand';
    }
    return $params;
}

// =============================================================================
// 9. RTS API SAFEGUARDS (Embed Widget Compatibility)
// Fixes CORS for Wix, bypasses aggressive caching (Hostinger/LiteSpeed)
// =============================================================================

add_action('rest_api_init', function() {
    // 1. FORCE CORS for Embeds (allows * origin for Wix/Squarespace/Etc)
    // Priority 15 runs after most standard headers
    add_filter('rest_pre_serve_request', function($value, $result, $request) {
        if (strpos($request->get_route(), '/rts/v1/embed') !== false) {
            // Remove standard headers if already set to avoid duplication/conflict
            header_remove('Access-Control-Allow-Origin');
            header_remove('Access-Control-Allow-Methods');
            header_remove('Access-Control-Allow-Headers');
            
            // Force permissive headers specifically for the widget
            header('Access-Control-Allow-Origin: *');
            header('Access-Control-Allow-Methods: GET, POST, OPTIONS');
            header('Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept');
            // Cache the pre-flight check for 24h to reduce server load
            header('Access-Control-Max-Age: 86400'); 
        }
        return $value;
    }, 15, 3);
});

// 2. BYPASS SERVER CACHING (LiteSpeed/WP Rocket) for "Random" endpoint
// This ensures the "Random" button actually works and doesn't serve the same letter repeatedly.
add_action('rest_post_dispatch', function($result, $server, $request) {
    if (strpos($request->get_route(), '/rts/v1/embed/random') !== false) {
        // Standard headers to kill browser/proxy cache
        header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
        header('Pragma: no-cache');
        header('Expires: Mon, 26 Jul 1997 05:00:00 GMT');
        
        // Hostinger / LiteSpeed specific bypass
        if (defined('LSCWP_V')) {
            do_action('litespeed_disable_cache');
            header('X-LiteSpeed-Cache-Control: no-cache');
        }
        
        // WP Rocket specific bypass
        if (function_exists('rocket_clean_domain')) {
            header('X-Rocket-Cache: miss');
        }
    }
    return $result;
}, 10, 3);

// 3. ALLOW PUBLIC ACCESS (Bypass "Require Login" / Security plugins)
// Whitelists the embed endpoint so it works even if the main site is locked down.
add_filter('rest_authentication_errors', function($result) {
    if (!empty($result)) {
        return $result;
    }
    // If request matches our embed API, allow it through
    if (isset($_SERVER['REQUEST_URI']) && strpos($_SERVER['REQUEST_URI'], '/rts/v1/embed') !== false) {
        return true; 
    }
    return $result;
});

// =============================================================================
// 10. SYNDICATION ENGINE (Embed Widgets)
// =============================================================================

require_once get_stylesheet_directory() . '/embeds/rts-embed-bootloader.php';
require_once get_stylesheet_directory() . '/inc/rts-embed-shortcodes.php';
require_once get_stylesheet_directory() . '/inc/rts-admin-manual.php';

/**
 * Admin menu order
 * Put Letters and Subscribers at the very top, just under Dashboard/Updates.
 */
add_filter('custom_menu_order', 'rts_custom_menu_order');
add_filter('menu_order', 'rts_menu_order');

function rts_custom_menu_order() {
    return true;
}

function rts_menu_order($menu_order) {
    if (!is_array($menu_order)) {
        return $menu_order;
    }

    $priority = array(
        'index.php',
        'separator1',
        'edit.php?post_type=letter',
        'edit.php?post_type=rts_subscriber',
    );

    // Keep only items that actually exist in current menu.
    $priority = array_values(array_intersect($priority, $menu_order));

    // Append the rest in original order.
    $rest = array_values(array_diff($menu_order, $priority));
    return array_merge($priority, $rest);
}